// Vitamin Village — shared data. Extracted from vitamin-village/index.html; keep in sync.

const CHARACTERS = [
  {id:"d",   name:"Sunny D", nutrient:"Vitamin D",  sym:"D",  bg:"#FAEEDA", ink:"#633806", jersey:"#E0A93E",
     does:"Helps your bones grow strong and keeps you feeling happy.", fact:"Your body makes Vitamin D when you play in the sun!"},
  {id:"cal", name:"Cal",     nutrient:"Calcium",    sym:"Ca", bg:"#E6F1FB", ink:"#0C447C", jersey:"#4E97DD",
     does:"Builds strong bones and healthy teeth.", fact:"Almost all your calcium lives in your bones and teeth!"},
  {id:"c",   name:"Vita C",  nutrient:"Vitamin C",  sym:"C",  bg:"#EAF3DE", ink:"#27500A", jersey:"#7DB33F",
     does:"Helps cuts heal and fights off sniffles.", fact:"A bell pepper has more Vitamin C than an orange!"},
  {id:"iron",name:"Iggy",    nutrient:"Iron",       sym:"Fe", bg:"#FAECE7", ink:"#712B13", jersey:"#D96B45",
     does:"Carries oxygen in your blood so you have energy.", fact:"Iron helps make your blood red!"},
  {id:"zinc",name:"Zippy",   nutrient:"Zinc",       sym:"Zn", bg:"#FBEAF0", ink:"#72243E", jersey:"#D75E8A",
     does:"Helps you grow and fight germs.", fact:"Zinc helps your body heal scrapes!"},
  {id:"mag", name:"Maggie",  nutrient:"Magnesium",  sym:"Mg", bg:"#E1F5EE", ink:"#085041", jersey:"#3BB58C",
     does:"Helps muscles relax and gives steady energy.", fact:"Magnesium helps with 300+ jobs in your body!"},
  {id:"a",   name:"Ava",     nutrient:"Vitamin A",  sym:"A",  bg:"#FDEBD9", ink:"#7A4409", jersey:"#E8963A",
     does:"Helps you see well and keeps skin healthy.", fact:"Carrots really can help you see in the dark!"},
  {id:"k",   name:"Kip",     nutrient:"Vitamin K2", sym:"K2", bg:"#EEEDFE", ink:"#3C3489", jersey:"#8E86E0",
     does:"Guides calcium to your bones.", fact:"Vitamin K helps cuts stop bleeding!"},
  {id:"cop", name:"Coop",    nutrient:"Copper",     sym:"Cu", bg:"#F4EBE0", ink:"#6B4423", jersey:"#B07B4F",
     does:"Helps your body use iron.", fact:"A little copper helps colour your hair and skin!"},
  {id:"e",   name:"Ellie",   nutrient:"Vitamin E",  sym:"E",  bg:"#FBF3D9", ink:"#7A6516", jersey:"#D4B24A",
     does:"Protects your cells like a shield.", fact:"Vitamin E teams up with Vita C to protect you!"},
];
const CH = Object.fromEntries(CHARACTERS.map(c => [c.id, c]));

const RULES = {
  cal_d:   {type:"buddy", verdict:"Best buddies!", kid:"Sunny D helps your tummy soak up Cal, so your bones grow big and strong.", timing:"Enjoy together"},
  c_iron:  {type:"buddy", verdict:"Best buddies!", kid:"Vita C grabs Iggy from your food so you stay full of zoom and energy.", timing:"Enjoy together"},
  d_mag:   {type:"buddy", verdict:"Best buddies!", kid:"Maggie gives Sunny D a friendly wake-up nudge so he can get to work.", timing:"Enjoy together"},
  cal_mag: {type:"buddy", verdict:"Good teammates!", kid:"Cal and Maggie work as a team for strong bones and calm muscles.", timing:"Enjoy together"},
  a_zinc:  {type:"buddy", verdict:"Best buddies!", kid:"Zippy helps carry Ava around your body so she can help you see!", timing:"Enjoy together"},
  a_iron:  {type:"buddy", verdict:"Best buddies!", kid:"Ava gives Iggy a helping hand so your blood stays strong.", timing:"Enjoy together"},
  d_k:     {type:"buddy", verdict:"Best buddies!", kid:"Sunny D lets calcium in, and Kip shows it the way to your bones!", timing:"Enjoy together"},
  cal_k:   {type:"buddy", verdict:"Best buddies!", kid:"Kip is Cal's guide, taking him straight to your bones and teeth.", timing:"Enjoy together"},
  cop_iron:{type:"buddy", verdict:"Best buddies!", kid:"Coop is Iggy's sidekick, helping your body use iron the right way.", timing:"Enjoy together"},
  c_e:     {type:"buddy", verdict:"Best buddies!", kid:"When Ellie gets tired, Vita C recharges her like a battery!", timing:"Enjoy together"},
  cal_iron:{type:"space", verdict:"Need some space!", kid:"These two squeeze through the same little door. Give them about 2 hours apart.", timing:"About 2 hours apart"},
  cal_zinc:{type:"space", verdict:"Need some space!", kid:"Cal and Zippy bump elbows, so give them a little gap.", timing:"A couple of hours apart"},
  iron_zinc:{type:"space",verdict:"Need some space!", kid:"Iggy and Zippy race for the same spot and slow each other down.", timing:"A couple of hours apart"},
  cop_zinc:{type:"space", verdict:"Need some space!", kid:"Zippy pushes past Coop at the door, so give them a gap.", timing:"A couple of hours apart"},
};
const BUDDY_KEYS = Object.keys(RULES).filter(k => RULES[k].type === "buddy");

const FOODS = [
  {name:"Avocado", cat:"Vegetable", has:["mag","e"]},
  {name:"Asparagus", cat:"Vegetable", has:["a","c","e"]},
  {name:"Kale", cat:"Leafy green", has:["cal","c","a"]},
  {name:"Spinach", cat:"Leafy green", has:["iron","mag","a","e"]},
  {name:"Broccoli", cat:"Vegetable", has:["cal","c","a"]},
  {name:"Cabbage", cat:"Leafy green", has:["c"]},
  {name:"Cucumber", cat:"Vegetable", has:["c"]},
  {name:"Celery", cat:"Vegetable", has:["c"]},
  {name:"Zucchini", cat:"Vegetable", has:["c","a"]},
  {name:"Eggplant", cat:"Vegetable", has:["mag","cop"]},
  {name:"Bell peppers", cat:"Vegetable", has:["c","a"]},
  {name:"Carrots", cat:"Vegetable", has:["a"]},
  {name:"Beets", cat:"Vegetable", has:["iron","mag"]},
  {name:"Radishes", cat:"Vegetable", has:["c"]},
  {name:"Sweet potato", cat:"Vegetable", has:["a","c"]},
  {name:"Pumpkin", cat:"Vegetable", has:["a"]},
  {name:"Butternut squash", cat:"Vegetable", has:["a","c"]},
  {name:"Tomatoes", cat:"Fruit", has:["c","a"]},
  {name:"Lettuce", cat:"Leafy green", has:["a"]},
  {name:"Arugula", cat:"Leafy green", has:["cal","a"]},
  {name:"Green beans", cat:"Vegetable", has:["c"]},
  {name:"Peas", cat:"Legume", has:["c","iron"]},
  {name:"Brussels sprouts", cat:"Vegetable", has:["c","a"]},
  {name:"Okra", cat:"Vegetable", has:["c","mag"]},
  {name:"Apples", cat:"Fruit", has:["c"]},
  {name:"Pears", cat:"Fruit", has:["c"]},
  {name:"Peaches", cat:"Fruit", has:["c","a"]},
  {name:"Apricots", cat:"Fruit", has:["a","c"]},
  {name:"Cherries", cat:"Fruit", has:["c"]},
  {name:"Plums", cat:"Fruit", has:["c"]},
  {name:"Mango", cat:"Fruit", has:["c","a"]},
  {name:"Papaya", cat:"Fruit", has:["c","a"]},
  {name:"Pineapple", cat:"Fruit", has:["c"]},
  {name:"Watermelon", cat:"Fruit", has:["c","a"]},
  {name:"Cantaloupe", cat:"Fruit", has:["a","c"]},
  {name:"Honeydew", cat:"Fruit", has:["c"]},
  {name:"Strawberries", cat:"Berry", has:["c"]},
  {name:"Blueberries", cat:"Berry", has:["c"]},
  {name:"Raspberries", cat:"Berry", has:["c"]},
  {name:"Blackberries", cat:"Berry", has:["c"]},
  {name:"Lemon", cat:"Citrus", has:["c"]},
  {name:"Lime", cat:"Citrus", has:["c"]},
  {name:"Grapefruit", cat:"Citrus", has:["c"]},
  {name:"Oranges", cat:"Citrus", has:["c"]},
  {name:"Bananas", cat:"Fruit", has:["c","mag"]},
  {name:"Figs", cat:"Fruit", has:["cal","mag"]},
  {name:"Grapes", cat:"Fruit", has:["c"]},
  {name:"Pomegranate", cat:"Fruit", has:["c"]},
  {name:"Almonds", cat:"Nut", has:["mag","e","cal"]},
  {name:"Brazil nuts", cat:"Nut", has:["mag","e","cop"]},
  {name:"Chia seeds", cat:"Seed", has:["cal","mag","iron"]},
  {name:"Flax seeds", cat:"Seed", has:["mag","cop"]},
  {name:"Hemp seeds", cat:"Seed", has:["mag","iron"]},
  {name:"Sesame seeds", cat:"Seed", has:["cal","cop","iron"]},
  {name:"Pumpkin seeds", cat:"Seed", has:["iron","zinc","mag"]},
  {name:"Sunflower seeds", cat:"Seed", has:["e","cop"]},
  {name:"Olive oil", cat:"Oil", has:["e"]},
  {name:"Seaweed", cat:"Sea vegetable", has:["iron","cal","a"]},
  {name:"Kelp", cat:"Sea vegetable", has:["iron","cal"]},
  {name:"Parsley", cat:"Herb", has:["c","a","iron"]},
  {name:"Cilantro", cat:"Herb", has:["a","c"]},
  {name:"Basil", cat:"Herb", has:["a"]},
  {name:"Oregano", cat:"Herb", has:["iron","cal"]},
  {name:"Thyme", cat:"Herb", has:["c","iron"]},
  {name:"Rosemary", cat:"Herb", has:["a","iron"]},
  {name:"Ginger root", cat:"Herb", has:["mag"]},
  {name:"Turmeric", cat:"Herb", has:["iron"]},
  {name:"Garlic", cat:"Vegetable", has:["c","cop"]},
  {name:"Onions", cat:"Vegetable", has:["c"]},
  {name:"Mushrooms", cat:"Vegetable", has:["d","cop"]},
  {name:"Leeks", cat:"Vegetable", has:["a","c"]},
  {name:"Turnips", cat:"Vegetable", has:["c"]},
  {name:"Parsnips", cat:"Vegetable", has:["c"]},
  {name:"Swiss chard", cat:"Leafy green", has:["a","iron","mag"]},
  {name:"Collard greens", cat:"Leafy green", has:["cal","a"]},
  {name:"Watercress", cat:"Leafy green", has:["a","c"]},
  {name:"Endive", cat:"Leafy green", has:["a"]},
  {name:"Brown rice", cat:"Grain", has:["mag"]},
  {name:"White rice", cat:"Grain", has:["iron"]},
  {name:"Oats", cat:"Grain", has:["zinc","mag","iron"]},
  {name:"Steel cut oats", cat:"Grain", has:["zinc","mag","iron"]},
  {name:"Barley", cat:"Grain", has:["mag","iron"]},
  {name:"Farro", cat:"Grain", has:["iron","mag"]},
  {name:"Quinoa", cat:"Grain", has:["mag","iron"]},
  {name:"Bulgur", cat:"Grain", has:["mag","iron"]},
  {name:"Couscous", cat:"Grain", has:["mag"]},
  {name:"Whole wheat", cat:"Grain", has:["mag","iron"]},
  {name:"Whole grain bread", cat:"Grain", has:["iron","mag"]},
  {name:"Bagels", cat:"Grain", has:["iron"]},
  {name:"Whole grain pasta", cat:"Grain", has:["iron","mag"]},
  {name:"Noodles", cat:"Grain", has:["iron"]},
  {name:"Corn", cat:"Vegetable", has:["mag"]},
  {name:"Sweet corn", cat:"Vegetable", has:["c","mag"]},
  {name:"White potatoes", cat:"Vegetable", has:["c"]},
  {name:"Red potatoes", cat:"Vegetable", has:["c"]},
  {name:"Chickpeas", cat:"Legume", has:["iron","zinc"]},
  {name:"Lentils", cat:"Legume", has:["iron","mag"]},
  {name:"Black beans", cat:"Legume", has:["iron","mag"]},
  {name:"Kidney beans", cat:"Legume", has:["iron","mag"]},
  {name:"Pinto beans", cat:"Legume", has:["iron","mag"]},
  {name:"Navy beans", cat:"Legume", has:["iron","mag"]},
  {name:"Cashews", cat:"Nut", has:["zinc","cop","mag"]},
  {name:"Pistachios", cat:"Nut", has:["e","cop"]},
  {name:"Walnuts", cat:"Nut", has:["cop","mag"]},
  {name:"Pecans", cat:"Nut", has:["cop","e"]},
  {name:"Tahini", cat:"Seed", has:["cal","cop","iron"]},
  {name:"Eggs", cat:"Protein", has:["d","a","k"]},
  {name:"Greek yogurt", cat:"Dairy", has:["cal","zinc"]},
  {name:"Plain yogurt", cat:"Dairy", has:["cal","zinc"]},
  {name:"Cottage cheese", cat:"Dairy", has:["cal"]},
  {name:"Ricotta", cat:"Dairy", has:["cal"]},
  {name:"Goat cheese", cat:"Dairy", has:["cal","k"]},
  {name:"Feta cheese", cat:"Dairy", has:["cal","k"]},
  {name:"Milk", cat:"Dairy", has:["cal","d"]},
  {name:"Almond milk", cat:"Dairy", has:["cal","e"]},
  {name:"Soy milk", cat:"Dairy", has:["cal"]},
  {name:"Oat milk", cat:"Dairy", has:["cal"]},
  {name:"Butter", cat:"Dairy", has:["a","k"]},
  {name:"Ghee", cat:"Dairy", has:["a"]},
  {name:"Salmon", cat:"Fish", has:["d"]},
  {name:"Tuna", cat:"Fish", has:["d"]},
  {name:"Sardines", cat:"Fish", has:["d","cal"]},
  {name:"Mackerel", cat:"Fish", has:["d"]},
  {name:"Chicken", cat:"Meat", has:["zinc","k"]},
  {name:"Turkey", cat:"Meat", has:["zinc","iron"]},
  {name:"Lean beef", cat:"Meat", has:["iron","zinc"]},
  {name:"Lamb", cat:"Meat", has:["iron","zinc"]},
  {name:"Avocado oil", cat:"Oil", has:["e"]},
  {name:"Canola oil", cat:"Oil", has:["e"]},
  {name:"Dark chocolate", cat:"Treat", has:["cop","mag","iron"]},
  {name:"Cocoa", cat:"Treat", has:["cop","mag","iron"]},
  {name:"Fruit juice", cat:"Drink", has:["c"]},
  {name:"Smoothies", cat:"Drink", has:["c"]},
  {name:"Granola", cat:"Grain", has:["iron","mag"]},
  {name:"Muesli", cat:"Grain", has:["iron","mag"]},
  {name:"Dried apricots", cat:"Dried fruit", has:["a","iron"]},
  {name:"Raisins", cat:"Dried fruit", has:["iron"]},
  {name:"Dried figs", cat:"Dried fruit", has:["cal","iron","mag"]},
  {name:"Dates", cat:"Dried fruit", has:["mag","cop"]},
  {name:"Coconut milk", cat:"Dairy", has:["iron","mag"]},
  {name:"Cream", cat:"Dairy", has:["cal","a"]},
];

// Recipes — three or four per buddy pair. Each puts a friendly nutrient team
// into one meal. `pair` links the recipe back to a rule in RULES.
const RECIPES = [
  {id:"r01", name:"Sunshine Breakfast Scramble", pair:["d","cal"], meal:"Breakfast", prep:10, serves:2,
   why:"Eggs bring Sunny D and cheese brings Cal — together they build strong bones!",
   ingredients:["4 eggs","2 tbsp milk","Handful of grated cheese","A little butter","Pinch of salt"],
   steps:["Crack the eggs into a bowl and add the milk.","Whisk until smooth.","Melt butter in a pan on low heat.","Pour in the eggs and stir gently.","Sprinkle in cheese and stir until fluffy."],
   shopping:["Eggs","Milk","Cheese","Butter"],
   parent:"Vitamin D from the yolks helps absorb calcium from the cheese and milk."},
  {id:"r02", name:"Sardine Toast Boats", pair:["d","cal"], meal:"Lunch", prep:10, serves:2,
   why:"Sardines are a double helper — they carry Sunny D AND Cal all by themselves!",
   ingredients:["1 tin sardines (drained)","2 slices whole grain bread","1 tbsp cream cheese","Squeeze of lemon","A few cucumber slices"],
   steps:["Toast the bread until golden.","Spread on the cream cheese.","Lay the sardines on top and break them up gently with a fork.","Squeeze on a little lemon.","Add cucumber slices and cut into boats."],
   shopping:["Sardines","Whole grain bread","Cream cheese","Lemon","Cucumber"],
   parent:"Tinned sardines (with soft edible bones) provide both vitamin D and calcium in one food."},
  {id:"r03", name:"Creamy Salmon Pasta", pair:["d","cal"], meal:"Dinner", prep:25, serves:4,
   why:"Salmon brings Sunny D and the creamy cheese sauce brings Cal — a bone-building dinner!",
   ingredients:["2 cups pasta","1 small salmon fillet","Half cup milk","Handful of grated cheese","Handful of peas","Pinch of salt"],
   steps:["Ask a grown-up to boil the pasta until soft.","Cook the salmon in a pan until it flakes apart.","Warm the milk in a pot and stir in the cheese until melted.","Add the peas to the sauce.","Mix the pasta, salmon and sauce together."],
   shopping:["Pasta","Salmon","Milk","Cheese","Peas"],
   parent:"Vitamin D from salmon supports absorption of calcium from the milk and cheese."},
  {id:"r04", name:"Rainbow Pepper & Bean Wrap", pair:["c","iron"], meal:"Lunch", prep:15, serves:2,
   why:"Bright peppers bring Vita C, which helps your body grab iron from the beans!",
   ingredients:["1 can black beans (drained)","1 red bell pepper (sliced)","1 yellow bell pepper (sliced)","2 tortilla wraps","A squeeze of lime"],
   steps:["Warm the beans in a pan.","Slice the peppers into strips.","Lay the wraps flat and add beans and peppers.","Squeeze on a little lime.","Roll up tightly and cut in half."],
   shopping:["Black beans","Red bell pepper","Yellow bell pepper","Tortilla wraps","Lime"],
   parent:"Vitamin C in the peppers strongly boosts absorption of plant-based iron from the beans."},
  {id:"r05", name:"Strawberry Spinach Salad", pair:["c","iron"], meal:"Lunch", prep:10, serves:2,
   why:"Strawberries bring Vita C right next to Iggy in the spinach — the perfect team!",
   ingredients:["2 handfuls baby spinach","1 cup strawberries (sliced)","2 tbsp pumpkin seeds","Drizzle of olive oil","Squeeze of lemon"],
   steps:["Wash the spinach and pat it dry.","Slice the strawberries.","Toss them together in a bowl.","Sprinkle over the pumpkin seeds.","Drizzle with oil and lemon and toss again."],
   shopping:["Baby spinach","Strawberries","Pumpkin seeds","Olive oil","Lemon"],
   parent:"Vitamin C from the strawberries and lemon helps the body absorb the iron in spinach and seeds."},
  {id:"r06", name:"Lentil & Tomato Soup", pair:["c","iron"], meal:"Dinner", prep:30, serves:4,
   why:"Tomatoes bring Vita C and lentils bring Iggy — a cosy bowl full of energy!",
   ingredients:["1 cup red lentils","1 can chopped tomatoes","1 carrot (chopped)","2 cups vegetable stock","Squeeze of lemon"],
   steps:["Ask a grown-up to add the lentils, tomatoes, carrot and stock to a pot.","Bring to a gentle boil.","Simmer until the lentils are soft.","Stir well and squeeze in the lemon.","Let it cool a little before serving."],
   shopping:["Red lentils","Chopped tomatoes","Carrot","Vegetable stock","Lemon"],
   parent:"Vitamin C from tomatoes and lemon boosts absorption of the iron in lentils."},
  {id:"r07", name:"Salmon & Spinach Rice Bowl", pair:["d","mag"], meal:"Dinner", prep:20, serves:2,
   why:"Salmon brings Sunny D and spinach brings Maggie for strong bones and calm energy!",
   ingredients:["2 small salmon fillets","2 handfuls spinach","1 cup cooked rice","2 tbsp pumpkin seeds","Drizzle of olive oil"],
   steps:["Ask a grown-up to heat a pan with a little oil.","Cook the salmon until it flakes.","Add the spinach for the last minute until soft.","Scoop rice into bowls.","Top with salmon, spinach and a sprinkle of pumpkin seeds."],
   shopping:["Salmon","Spinach","Rice","Pumpkin seeds","Olive oil"],
   parent:"Magnesium from spinach and seeds is needed to activate the vitamin D from salmon."},
  {id:"r08", name:"Mushroom & Oat Risotto", pair:["d","mag"], meal:"Dinner", prep:30, serves:4,
   why:"Mushrooms bring Sunny D and oats bring Maggie — a creamy, cosy dinner!",
   ingredients:["1 cup oats (steel cut)","2 cups sliced mushrooms","2 cups vegetable stock","Handful of grated cheese","Pinch of salt"],
   steps:["Ask a grown-up to fry the mushrooms until golden.","Add the oats and stir for a minute.","Pour in the stock a little at a time, stirring.","Cook until creamy and soft.","Stir in the cheese and serve warm."],
   shopping:["Steel cut oats","Mushrooms","Vegetable stock","Cheese"],
   parent:"Sun-grown mushrooms provide vitamin D; oats bring magnesium, which helps activate it."},
  {id:"r09", name:"Tuna & Avocado Sandwich", pair:["d","mag"], meal:"Lunch", prep:10, serves:2,
   why:"Tuna brings Sunny D and creamy avocado brings Maggie — lunchbox teamwork!",
   ingredients:["1 tin tuna (drained)","1 ripe avocado","4 slices whole grain bread","Squeeze of lemon","Pinch of salt"],
   steps:["Mash the avocado in a bowl with a fork.","Squeeze in the lemon and add a pinch of salt.","Stir in the tuna.","Spread onto two slices of bread.","Top with the other slices and cut in half."],
   shopping:["Tuna","Avocado","Whole grain bread","Lemon"],
   parent:"Vitamin D from tuna pairs with magnesium from avocado, which the body needs to use it."},
  {id:"r10", name:"Creamy Almond Yogurt Bowl", pair:["cal","mag"], meal:"Breakfast", prep:5, serves:2,
   why:"Yogurt brings Cal and almonds bring Maggie — teammates for bones and happy muscles!",
   ingredients:["1 cup plain yogurt","2 tbsp sliced almonds","1 tbsp pumpkin seeds","1 banana (sliced)","Drizzle of honey"],
   steps:["Spoon the yogurt into bowls.","Add the banana slices on top.","Sprinkle over the almonds and pumpkin seeds.","Drizzle with a little honey."],
   shopping:["Yogurt","Almonds","Pumpkin seeds","Banana","Honey"],
   parent:"Calcium from yogurt and magnesium from nuts and seeds support bones and muscles together. Check for nut allergies."},
  {id:"r11", name:"Cheesy Black Bean Quesadilla", pair:["cal","mag"], meal:"Lunch", prep:15, serves:2,
   why:"Cheese brings Cal and black beans bring Maggie — melty and mighty!",
   ingredients:["1 can black beans (drained)","Handful of grated cheese","2 tortilla wraps","A little butter","Pinch of salt"],
   steps:["Mash the beans lightly with a fork.","Spread them over one wrap and sprinkle on the cheese.","Top with the second wrap.","Ask a grown-up to cook it in a buttered pan until golden on both sides.","Cut into triangles."],
   shopping:["Black beans","Cheese","Tortilla wraps","Butter"],
   parent:"Calcium from cheese and magnesium from black beans work together for bones and muscles."},
  {id:"r12", name:"Fig & Almond Milk Smoothie", pair:["cal","mag"], meal:"Snack", prep:5, serves:2,
   why:"Figs and almond milk carry both Cal and Maggie — a sweet double team!",
   ingredients:["4 dried figs (soaked)","1 cup almond milk","1 banana","2 tbsp plain yogurt","A few ice cubes"],
   steps:["Soak the figs in warm water for a few minutes.","Add everything to a blender.","Put the lid on tightly.","Ask a grown-up to blend until smooth.","Pour into cups and enjoy cold."],
   shopping:["Dried figs","Almond milk","Banana","Yogurt"],
   parent:"Figs and fortified almond milk both provide calcium and magnesium. Check for nut allergies."},
  {id:"r13", name:"Carrot & Chickpea Hummus Dippers", pair:["a","zinc"], meal:"Snack", prep:10, serves:4,
   why:"Carrots bring Ava and chickpea hummus brings Zippy, who helps your body use Ava!",
   ingredients:["3 carrots (cut into sticks)","1 can chickpeas (drained)","1 tbsp olive oil","Squeeze of lemon","Pinch of salt"],
   steps:["Cut the carrots into sticks.","Add chickpeas, oil, lemon and salt to a blender.","Ask a grown-up to blend until smooth.","Scoop into a bowl.","Dip the carrot sticks and enjoy!"],
   shopping:["Carrots","Chickpeas","Olive oil","Lemon"],
   parent:"Vitamin A from carrots teams with zinc from chickpeas, which helps the body transport vitamin A."},
  {id:"r14", name:"Sweet Potato & Turkey Chili", pair:["a","zinc"], meal:"Dinner", prep:30, serves:4,
   why:"Sweet potato brings Ava and turkey brings Zippy — a warm bowl of teamwork!",
   ingredients:["1 sweet potato (cubed)","1 cup minced turkey","1 can chopped tomatoes","1 can kidney beans (drained)","Pinch of salt"],
   steps:["Ask a grown-up to brown the turkey in a pot.","Add the sweet potato, tomatoes and beans.","Stir well and bring to a gentle simmer.","Cook until the sweet potato is soft.","Let it cool a little before serving."],
   shopping:["Sweet potato","Minced turkey","Chopped tomatoes","Kidney beans"],
   parent:"Zinc from turkey helps the body transport and use the vitamin A from sweet potato."},
  {id:"r15", name:"Pumpkin Seed Sweet Potato Toast", pair:["a","zinc"], meal:"Snack", prep:15, serves:2,
   why:"Sweet potato brings Ava and pumpkin seeds bring Zippy — crunchy and orange!",
   ingredients:["1 large sweet potato","2 tbsp pumpkin seeds","1 tbsp cream cheese","Drizzle of olive oil","Pinch of salt"],
   steps:["Ask a grown-up to slice the sweet potato into thick rounds.","Toast or bake the rounds until soft.","Spread on a little cream cheese.","Sprinkle over the pumpkin seeds.","Add a pinch of salt and enjoy."],
   shopping:["Sweet potato","Pumpkin seeds","Cream cheese","Olive oil"],
   parent:"Vitamin A from sweet potato pairs with zinc from pumpkin seeds, which helps the body use it."},
  {id:"r16", name:"Lentil & Sweet Potato Stew", pair:["a","iron"], meal:"Dinner", prep:30, serves:4,
   why:"Lentils bring Iggy and sweet potato brings Ava, who helps your blood stay strong!",
   ingredients:["1 cup red lentils","1 sweet potato (cubed)","1 carrot (chopped)","2 cups vegetable stock","Pinch of salt"],
   steps:["Ask a grown-up to add everything to a pot.","Bring to a gentle boil.","Simmer until the lentils and sweet potato are soft.","Stir well.","Let it cool a little before serving."],
   shopping:["Red lentils","Sweet potato","Carrot","Vegetable stock"],
   parent:"Iron from lentils pairs with vitamin A from sweet potato and carrot, which supports iron use."},
  {id:"r17", name:"Spinach & Apricot Couscous", pair:["a","iron"], meal:"Lunch", prep:15, serves:2,
   why:"Spinach and dried apricots both carry Ava and Iggy — a double-double team!",
   ingredients:["1 cup couscous","2 handfuls spinach","6 dried apricots (chopped)","1 cup hot vegetable stock","Drizzle of olive oil"],
   steps:["Put the couscous in a bowl.","Ask a grown-up to pour over the hot stock, then cover for 5 minutes.","Fluff it up with a fork.","Stir through the spinach until it wilts.","Add the apricots and a drizzle of oil."],
   shopping:["Couscous","Spinach","Dried apricots","Vegetable stock","Olive oil"],
   parent:"Spinach and dried apricots each provide both iron and vitamin A, which supports iron use."},
  {id:"r18", name:"Beef & Carrot Skillet", pair:["a","iron"], meal:"Dinner", prep:25, serves:4,
   why:"Beef brings Iggy and carrots bring Ava — a hearty pan of helpers!",
   ingredients:["1 cup minced lean beef","2 carrots (sliced)","1 cup cooked rice","1 tbsp tomato paste","Pinch of salt"],
   steps:["Ask a grown-up to brown the beef in a pan.","Add the sliced carrots and cook until soft.","Stir in the tomato paste.","Add the cooked rice and mix well.","Season lightly and serve warm."],
   shopping:["Minced lean beef","Carrots","Rice","Tomato paste"],
   parent:"Iron from beef is easily absorbed, and vitamin A from carrots helps the body mobilize iron."},
  {id:"r19", name:"Cheesy Egg Muffins", pair:["d","k"], meal:"Breakfast", prep:25, serves:6,
   why:"Eggs bring Sunny D and cheese brings Kip, who guides calcium to your bones!",
   ingredients:["6 eggs","Half cup grated cheese","Splash of milk","Chopped veggies (optional)","Pinch of salt"],
   steps:["Ask a grown-up to heat the oven to 375F (190C).","Whisk the eggs, milk and salt.","Stir in the cheese and veggies.","Pour into a greased muffin tray.","Bake until set and golden."],
   shopping:["Eggs","Cheese","Milk","Muffin tray"],
   parent:"Vitamin D from eggs and vitamin K2 from cheese and yolks work as a bone-building team."},
  {id:"r20", name:"Mushroom & Chicken Skewers", pair:["d","k"], meal:"Dinner", prep:25, serves:4,
   why:"Mushrooms bring Sunny D and chicken brings Kip — dinner on a stick!",
   ingredients:["1 cup mushrooms (whole)","2 chicken breasts (cubed)","1 bell pepper (chunked)","Drizzle of olive oil","Pinch of salt"],
   steps:["Ask a grown-up to help thread the chicken, mushrooms and pepper onto skewers.","Brush with a little oil and salt.","Grill or bake, turning once, until the chicken is cooked through.","Let them cool a little.","Slide everything off the skewer before eating."],
   shopping:["Mushrooms","Chicken breasts","Bell pepper","Olive oil","Skewers"],
   parent:"Sun-grown mushrooms provide vitamin D; chicken provides vitamin K2."},
  {id:"r21", name:"Egg & Butter Soldiers", pair:["d","k"], meal:"Breakfast", prep:10, serves:2,
   why:"Eggs carry both Sunny D and Kip, and buttery toast brings even more Kip!",
   ingredients:["2 eggs","2 slices whole grain bread","A little butter","Pinch of salt"],
   steps:["Ask a grown-up to boil the eggs for about 5 minutes for a runny yolk.","Toast the bread and spread with butter.","Cut the toast into long strips (soldiers).","Pop the top off each egg.","Dip the soldiers into the yolk!"],
   shopping:["Eggs","Whole grain bread","Butter"],
   parent:"Egg yolks provide both vitamin D and vitamin K2; butter adds a little more K2."},
  {id:"r22", name:"Cheesy Broccoli Trees", pair:["cal","k"], meal:"Dinner", prep:20, serves:4,
   why:"Cheese carries both Cal and Kip, so the calcium heads straight to your bones!",
   ingredients:["1 head broccoli (in florets)","Half cup grated cheese","Drizzle of olive oil","Pinch of salt"],
   steps:["Ask a grown-up to heat the oven to 400F (200C).","Toss the broccoli with oil and salt on a tray.","Roast until tender.","Sprinkle the cheese on top.","Return to the oven until the cheese melts."],
   shopping:["Broccoli","Cheese","Olive oil"],
   parent:"Cheese provides both calcium and vitamin K2, which helps steer calcium into bones."},
  {id:"r23", name:"Goat Cheese & Collard Wraps", pair:["cal","k"], meal:"Lunch", prep:15, serves:2,
   why:"Collard greens bring Cal and goat cheese brings both Cal and Kip!",
   ingredients:["4 large collard green leaves","Half cup goat cheese","1 carrot (grated)","Half cucumber (sliced)","Squeeze of lemon"],
   steps:["Wash the collard leaves and pat them dry.","Ask a grown-up to trim the thick stems.","Spread goat cheese down the middle of each leaf.","Add the grated carrot and cucumber.","Roll up tightly and cut in half."],
   shopping:["Collard greens","Goat cheese","Carrot","Cucumber","Lemon"],
   parent:"Collard greens and goat cheese both provide calcium; the cheese also provides vitamin K2."},
  {id:"r24", name:"Feta & Cucumber Crunch", pair:["cal","k"], meal:"Snack", prep:10, serves:2,
   why:"Feta is a double helper — it carries Cal AND Kip in one crumbly cube!",
   ingredients:["Half cup feta cheese (cubed)","1 cucumber (chopped)","Handful of cherry tomatoes","Drizzle of olive oil","Pinch of oregano"],
   steps:["Chop the cucumber into chunks.","Halve the cherry tomatoes.","Add the feta cubes to a bowl with the veggies.","Drizzle with olive oil.","Sprinkle over the oregano and toss gently."],
   shopping:["Feta cheese","Cucumber","Cherry tomatoes","Olive oil","Oregano"],
   parent:"Feta provides calcium along with vitamin K2, which helps direct calcium into bone."},
  {id:"r25", name:"Choco-Oat Energy Balls", pair:["cop","iron"], meal:"Snack", prep:15, serves:6,
   why:"Oats bring Iggy and dark chocolate brings Coop, who helps your body use iron!",
   ingredients:["1 cup oats","Half cup peanut butter","3 tbsp honey","2 tbsp dark chocolate chips","2 tbsp chopped cashews"],
   steps:["Mix the oats, peanut butter and honey in a bowl.","Stir in the chocolate chips and cashews.","Roll into small balls with clean hands.","Chill in the fridge for 30 minutes."],
   shopping:["Oats","Peanut butter","Honey","Dark chocolate chips","Cashews"],
   parent:"Iron from oats teams with copper from dark chocolate and cashews. Check for nut allergies."},
  {id:"r26", name:"Cashew & Lentil Curry", pair:["cop","iron"], meal:"Dinner", prep:30, serves:4,
   why:"Lentils bring Iggy and cashews bring Coop — a creamy, cosy dinner duo!",
   ingredients:["1 cup red lentils","Half cup cashews","1 can coconut milk","1 tsp mild curry powder","1 cup vegetable stock"],
   steps:["Ask a grown-up to add the lentils and stock to a pot.","Simmer until the lentils soften.","Stir in the coconut milk and curry powder.","Add the cashews and cook a few minutes more.","Serve warm with rice."],
   shopping:["Red lentils","Cashews","Coconut milk","Curry powder","Vegetable stock"],
   parent:"Copper from cashews helps the body properly use the iron from lentils. Check for nut allergies."},
  {id:"r27", name:"Sesame Beef Noodles", pair:["cop","iron"], meal:"Dinner", prep:25, serves:4,
   why:"Beef brings Iggy and sesame seeds bring Coop — slurpy noodle teamwork!",
   ingredients:["1 cup minced lean beef","2 tbsp sesame seeds","2 cups cooked noodles","1 bell pepper (sliced)","1 tbsp soy sauce"],
   steps:["Ask a grown-up to brown the beef in a pan.","Add the sliced pepper and cook until soft.","Toss in the cooked noodles.","Add the soy sauce and stir well.","Sprinkle the sesame seeds over the top."],
   shopping:["Minced lean beef","Sesame seeds","Noodles","Bell pepper","Soy sauce"],
   parent:"Sesame seeds provide copper, which the body needs to use the iron from beef."},
  {id:"r28", name:"Berry & Almond Yogurt Parfait", pair:["c","e"], meal:"Snack", prep:10, serves:2,
   why:"Berries bring Vita C and almonds bring Ellie — Vita C recharges Ellie like a battery!",
   ingredients:["1 cup yogurt","Half cup strawberries (sliced)","1 kiwi (sliced)","2 tbsp sliced almonds","Drizzle of honey"],
   steps:["Spoon a layer of yogurt into a clear cup.","Add a layer of berries and kiwi.","Repeat the layers.","Top with almonds and a drizzle of honey."],
   shopping:["Yogurt","Strawberries","Kiwi","Almonds","Honey"],
   parent:"Vitamin C from the berries recharges vitamin E from the almonds. Check for nut allergies."},
  {id:"r29", name:"Avocado & Orange Salad", pair:["c","e"], meal:"Lunch", prep:10, serves:2,
   why:"Oranges bring Vita C and creamy avocado brings Ellie — sunshine in a bowl!",
   ingredients:["1 ripe avocado (sliced)","2 oranges (peeled and sliced)","2 handfuls lettuce","Drizzle of olive oil","Pinch of salt"],
   steps:["Peel and slice the oranges into rounds.","Slice the avocado.","Lay the lettuce on a plate.","Arrange the orange and avocado on top.","Drizzle with oil and add a pinch of salt."],
   shopping:["Avocado","Oranges","Lettuce","Olive oil"],
   parent:"Vitamin C from oranges helps regenerate vitamin E from avocado and olive oil."},
  {id:"r30", name:"Sunflower Broccoli Crunch", pair:["c","e"], meal:"Snack", prep:10, serves:2,
   why:"Broccoli brings Vita C and sunflower seeds bring Ellie — crunchy little trees!",
   ingredients:["1 head broccoli (small florets)","2 tbsp sunflower seeds","2 tbsp plain yogurt","Squeeze of lemon","Pinch of salt"],
   steps:["Chop the broccoli into small florets.","Mix the yogurt, lemon and salt to make a dip.","Toast the sunflower seeds in a dry pan for a minute.","Toss the broccoli with the seeds.","Serve with the dip on the side."],
   shopping:["Broccoli","Sunflower seeds","Yogurt","Lemon"],
   parent:"Vitamin C from broccoli and lemon recharges vitamin E from the sunflower seeds."},
  {id:"r31", name:"Berry Oat Porridge", pair:["c","iron"], meal:"Breakfast", prep:10, serves:2,
   why:"Oats bring Iggy and the berries on top bring Vita C to help him along!",
   ingredients:["1 cup oats","2 cups milk","Half cup mixed berries","1 tbsp honey","Pinch of salt"],
   steps:["Ask a grown-up to warm the oats and milk in a pot.","Stir gently until thick and creamy.","Spoon into bowls.","Pile the berries on top.","Drizzle with a little honey."],
   shopping:["Oats","Milk","Mixed berries","Honey"],
   parent:"Vitamin C from the berries helps the body absorb the iron in the oats."},
  {id:"r32", name:"Fig & Oat Porridge", pair:["cal","mag"], meal:"Breakfast", prep:10, serves:2,
   why:"Figs carry both Cal and Maggie, and the oats bring even more Maggie!",
   ingredients:["1 cup oats","2 cups milk","4 dried figs (chopped)","1 tbsp sliced almonds","Pinch of cinnamon"],
   steps:["Chop the figs into small pieces.","Ask a grown-up to warm the oats and milk in a pot.","Stir in the figs and cook until creamy.","Spoon into bowls.","Top with almonds and a pinch of cinnamon."],
   shopping:["Oats","Milk","Dried figs","Almonds","Cinnamon"],
   parent:"Figs and milk provide calcium; figs, oats and almonds provide magnesium. Check for nut allergies."},
  {id:"r33", name:"Sweet Potato Breakfast Hash", pair:["a","zinc"], meal:"Breakfast", prep:20, serves:4,
   why:"Sweet potato brings Ava and pumpkin seeds bring Zippy — a sunny start!",
   ingredients:["1 sweet potato (small cubes)","2 tbsp pumpkin seeds","1 bell pepper (chopped)","Drizzle of olive oil","Pinch of salt"],
   steps:["Ask a grown-up to heat a pan with a little oil.","Add the sweet potato cubes and cook until soft.","Stir in the chopped pepper.","Cook a few minutes more until everything is tender.","Sprinkle the pumpkin seeds over the top."],
   shopping:["Sweet potato","Pumpkin seeds","Bell pepper","Olive oil"],
   parent:"Zinc from pumpkin seeds helps the body transport the vitamin A from sweet potato."},
  {id:"r34", name:"Spinach & Mushroom Omelette", pair:["d","mag"], meal:"Breakfast", prep:15, serves:2,
   why:"Mushrooms bring Sunny D and spinach brings Maggie to wake him up!",
   ingredients:["3 eggs","1 cup sliced mushrooms","2 handfuls spinach","A little butter","Pinch of salt"],
   steps:["Whisk the eggs in a bowl with a pinch of salt.","Ask a grown-up to fry the mushrooms in butter until golden.","Add the spinach and stir until it wilts.","Pour the eggs over the top.","Cook until set, then fold in half and slide onto a plate."],
   shopping:["Eggs","Mushrooms","Spinach","Butter"],
   parent:"Vitamin D from mushrooms and eggs pairs with magnesium from spinach, which activates it."},
];

// ---- Flavour families, used by the Combo Maker (screen 5) ----------------
// The problem: a buddy pair like Vita C + Iron has 53 x 45 = 2,385 possible
// food combos, and plenty of them taste awful (sardines + strawberries!).
// Rather than hand-check thousands, we DERIVE a flavour family from the
// `cat` we already store, and refuse to mix sweet with savoury. One small
// rule tidies the whole space — and it costs no extra data.
const RECIPE_EMOJI = {
  "r01":"🍳","r02":"🐟","r03":"🍝","r04":"🌯","r05":"🥗","r06":"🍲",
  "r07":"🍚","r08":"🍄","r09":"🥪","r10":"🥣","r11":"🫔","r12":"🥤",
  "r13":"🥕","r14":"🌶","r15":"🍠","r16":"🥘","r17":"🍋","r18":"🥩",
  "r19":"🧁","r20":"🍗","r21":"🍞","r22":"🥦","r23":"🥗","r24":"🧀",
  "r25":"🍫","r26":"🍛","r27":"🍜","r28":"🍓","r29":"🥑","r30":"🥦",
  "r31":"🫐","r32":"🍑","r33":"🍠","r34":"🍳",
};
